import type { CampaignInput, InfluencerInput } from "./api";

export const demoCampaigns: CampaignInput[] = [
  {
    id: "camp-demo-001",
    brand_name: "Luma Beauty",
    goal: "Launch a summer skincare line",
    target_region: "Thailand",
    target_age_range: "18-24",
    budget: 25000,
    description:
      "Skincare and beauty focus for humid climates with glow routines.",
  },
  {
    id: "camp-demo-002",
    brand_name: "Pulse Activewear",
    goal: "Drive Q3 performance leggings sales",
    target_region: "Singapore",
    target_age_range: "25-34",
    budget: 38000,
    description: "Performance apparel drop for urban runners and gym creators.",
  },
  {
    id: "camp-demo-003",
    brand_name: "Nomad Coffee",
    goal: "Expand cold brew subscriptions",
    target_region: "Indonesia",
    target_age_range: "21-30",
    budget: 18000,
    description: "Lifestyle and café culture with focus on at-home rituals.",
  },
];

export const demoInfluencers: InfluencerInput[] = [
  {
    id: "inf-101",
    name: "GlowWithMaya",
    platform: "Instagram",
    category: "beauty",
    followers: 120000,
    engagement_rate: 0.072,
    region: "Thailand",
    languages: ["Thai", "English"],
    audience_age_range: "18-24",
    bio: "Thai beauty creator sharing skincare routines for humid climates.",
  },
  {
    id: "inf-102",
    name: "SkinScienceNate",
    platform: "YouTube",
    category: "skincare",
    followers: 85000,
    engagement_rate: 0.048,
    region: "Singapore",
    languages: ["English"],
    audience_age_range: "25-34",
    bio: "Science-first skincare breakdowns and deep-dive product reviews.",
  },
  {
    id: "inf-103",
    name: "BangkokGlow",
    platform: "TikTok",
    category: "beauty",
    followers: 210000,
    engagement_rate: 0.065,
    region: "Thailand",
    languages: ["Thai"],
    audience_age_range: "18-24",
    bio: "Short-form skincare and makeup content for Gen-Z in Bangkok.",
  },
  {
    id: "inf-104",
    name: "DermCarePro",
    platform: "Instagram",
    category: "skincare",
    followers: 60000,
    engagement_rate: 0.055,
    region: "Thailand",
    languages: ["Thai", "English"],
    audience_age_range: "25-34",
    bio: "Dermatology-backed tips and product recommendations.",
  },
  {
    id: "inf-105",
    name: "FitAndGlow",
    platform: "YouTube",
    category: "fitness",
    followers: 150000,
    engagement_rate: 0.035,
    region: "Thailand",
    languages: ["Thai"],
    audience_age_range: "18-34",
    bio: "Fitness, nutrition and wellness content with a focus on glow-up.",
  },
  {
    id: "inf-106",
    name: "SeaBreezeBeauty",
    platform: "Instagram",
    category: "beauty",
    followers: 95000,
    engagement_rate: 0.061,
    region: "Vietnam",
    languages: ["Vietnamese", "English"],
    audience_age_range: "18-24",
    bio: "Beach-friendly skincare and makeup for Southeast Asia climate.",
  },
];
